### ISSUE TITLE
Calculate the _id from folder names if `_id` file is missing

### ISSUE THREAD

**Issue by BigBlueHat** [jo/couch-push#5]
First, thanks for building this! :smile: 

Second, it'd be great to mimic the `couchapp.py` behavior (and `erica` also, iirc), such the `doc._id` can be calculated out of the current file or directory name--if it's missing in the JSON or as an `_id` file.

Without that, there's a migration process needed when moving between CouchApp tools--which would be great to avoid.

Thanks again!

**Comment by jo** [comment]
Thats a good idea.

**Comment by BigBlueHat** [comment]
It's just how [couchapp.py](http://github.com/couchapp/couchapp) works. :smiley:

My hope is to get more of these CouchApp tools to match and co-exist better.

I've added couch-push to the [CouchApp tools that support the filesystem mapping](https://github.com/couchapp/couchapp/wiki/Complete-Filesystem-to-Design-Doc-Mapping-Example). Feel free to clarify anything there.

Cheers!

**Comment by jo** [comment]
While I agree that a consensus on the filesystem mapping structure is a huge benefit, I do not so much like the `_docs` mapping...

**Comment by BigBlueHat** [comment]
Agreed. My projects look more like this these days:
```
_design/
  app/
  other_app/
_docs/
  doc1.json
  doc2.json

But that's only when I've got docs that I want controlled by the filesystem.

`_docs` confuses people when it's under `_design` as that's not where it ends up in CouchDB.

I'd love to actually spec out the filesystem mapping with some implementation tests...but...time. :)

Thanks for building this, @jo!

**Comment by jo** [comment]
Done in `1.2.0` with jo/couch-compile@b756ff3d0e9265ee151e01210c36ca2989daaa8f via 10d002158ad48324419b4731b9cffbca6aedba76
