### ISSUE TITLE
Support for CommonJS within Couchdb - what am I missing?

### ISSUE THREAD

**Issue by geekytime** [jo/couch-push#6]
I'd like to use couchdb's [internal support for CommonJS modules](http://docs.couchdb.org/en/latest/query-server/javascript.html#commonjs-modules). I'd think I'd be able to create my design document like this:

```
module.exports = {
  _id: "_design/app",
  language: "javascript",
  views: {
    lib: {
      requireField: function(doc, fieldName){
         if (!doc.hasOwnProperty(fieldName)){
           throw({forbidden: "missing field: " + fieldName});
         }
      }
    }
  },
  validate_doc_update: function(newDoc, oldDoc, userCtx){
    var requireField = require("views/lib/requireField");
    requireField(newDoc);
  }
};
```

When couch-push compiles my commonjs code, it converts the requireField function to a string as expected for a view, but in this case, we'd need a `module.exports = ` prepended to that string, so that requireField actually exports something.

I don't see an obvious way to make this work without a pull request, but I figured I'd ask before I start thinking about a potential solution.

**Comment by geekytime** [comment]
Now that I think about it, I guess this might be a better question for the couch-compile project...

**Comment by geekytime** [comment]
After futzing around with it a bit more, I was able to workaround the issue in a very reasonable way by defining my functions separately, and `toString()`ing them myself.

```
var requireField = function(doc, fieldName){
   if (!doc.hasOwnProperty(fieldName)){
     throw({forbidden: "missing field: " + fieldName});
   }
}

module.exports = {
  _id: "_design/app",
  language: "javascript",
  views: {
    lib: {
      requireField: "module.exports = " + requireField.toString()
    }
  },
  validate_doc_update: function(newDoc, oldDoc, userCtx){
    var requireField = require("views/lib/requireField");
    requireField(newDoc);
  }
};
```

**Comment by jo** [comment]
cool.
